apiVersion: v1
kind: Pod
metadata:
  name: pod-a
spec:
  containers:
  - name: container-a
    image: nginx:latest
    resources:
      limits:
        memory: "400Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
spec:
  containers:
  - name: container-b
    image: httpd:latest
    resources:
      limits:
        memory: "200Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
spec:
  containers:
  - name: container-c
    image: redis:6.0-alpine
    resources:
      limits:
        memory: "400Mi"
