apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
   CODE_CONFIG: |
   USERNAME: myuser
   HOSTNAME: localhost
   URI: https://example.com/api
   URL: https://example.com
   connection-string: |
    jdbc:mysql://localhost:3306/mydb?user=myuser&password=mypass

